### ISSUE TITLE
Use a destination to store the CF API credentials

### ISSUE THREAD

**Issue by gregorwolf** [saphanaacademy/generator-saphanaacademy-saas#2]
Hello SAP HANA Academy Team,

when running this generator and choosing "Yes" for the option "Would you like to include creation/deletion of tenant routes on subscribe/unsubscribe (using the CF API)?" the output after the generation is:

Important: The CF API is being used so please be sure to issue the following CF CLI commands after deployment:

```
  cf set-env mt-app-srv cf_api_user '<email>'
  cf set-env mt-app-srv cf_api_password '<password>'
```

I don't think that this is a good practice and would suggest to replace this by suggesting to create a destination named e.g. "CFAPI" with the Authentication OAuth2Password and store all required details there. Using this destination should allow also to use the SAP Cloud SDK for Javascript. As documentd in [Authentication and JSON Web Token Retrieval](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#authentication-and-json-web-token-retrieval) it supports OAuth2Password. So for all requests to the Cloud Foundry API the [Generic HTTP Client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client) could be used.

Best Regards
Gregor

**Comment by saphanaacademy** [comment]
Hello Gregor,

Thanks for your feedback and the suggestion. Indeed using environment variables is not a great option.

The equivalent capability in the [CAP generator](https://github.com/saphanaacademy/generator-saphanaacademy-cap) already offers the possibility to use the SAP Credential Store rather than environment variables.

However using the destination service is another excellent option - we'll look at incorporating that in the future.

Best regards,
Philip

**Comment by gregorwolf** [comment]
Hi Philip,

please find here a first sample how to call the Cloud Foundry API using a Destination

```javascript
const { executeHttpRequest } = require("@sap-cloud-sdk/core");

const destination = {
  destinationName: process.env.CFAPI_DESTINATION || "CFAPI",
};

async function getOrganizations() {
  const response = await executeHttpRequest(destination, {
    method: "get",
    url: "/v3/organizations",
  });
  return response.data;
}

module.exports = { getOrganizations };
```

The configuration is straight forward. Please note that the Client Secret is empty:

<img width="526" alt="Screenshot 2022-01-29 at 00 32 52" src="https://user-images.githubusercontent.com/2639535/151635584-9e2e81ab-a003-49fe-b98d-9448cb2fa666.png">

Don't think that Credential Store is the right option as then you still have to maintain the URL and Token Service URL somewhere else.

Best Regards
Gregor

**Comment by saphanaacademy** [comment]
Hi Gregor,

Thanks for sharing the example.

The latest version of the saphanaacademy-saas and saphanaacademy-cap generators now support accessing the CF API via a destination and Cloud SDK rather than via environment variables or SAP Credential Store. An instance destination <projectName>-cfapi is created during MTA deployment (see the definition in mta.yaml).

After app deployment but before subscribing/unsubscribing a tenant, the instance destination <projectName>-cfapi needs to have the user and password set (technical user recommended) and also the token service URL should have "login" changed to "uaa" at the beginning (or you can manually set this in mta/yaml). The BTP cockpit requires fresh values for password and client secret whenever a URL is changed. However client secret should be empty! Workaround this by entering a value and saving then re-editing and setting the password back to empty and saving again.

Hands-on video tutorials showing the whole process to come...

Best regards,
Philip

**Comment by piejanssens** [comment]
Hi Philip,

Just a quick FYI regarding this topic:

- The secret being mandatory (while not indicated as mandatory): I filed this in incident 4093127 / 2022
- Using `uaa` instead of `login` in the URL does not seem to make a difference, so this instruction can be left out. If there is a difference, I'd be interested to know how it differs. 

Best regards,

Pieter
